config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes

  root 'recipes#index'

  get 'your_recipes' => 'recipes#your_recipes'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password,
    :password_confirmation, :name, :username, :homecountry) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password,
   :password_confirmation, :current_password, :name, :username, :homecountry) }
 end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  def your_recipes
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :instructions, :rating, :user_id, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <meta charset="utf=8">
  <meta charset="utf=8">
  <meta http=equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <% if user_signed_in? %>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Recipes", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Your Profile", your_recipes_path %></li>
        <li><%= link_to "New Recipe", new_recipe_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-default" %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <% end %>
    <%= yield %>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "sr-only" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, class:"sr-only" %>
    <%= f.text_area :ingredients, class: "form-control", placeholder: "Ingredients" %>
  </div>
  <div class="form-group">
    <%= f.label :instructions, class:"sr-only" %>
    <%= f.text_area :instructions, class: "form-control", placeholder: "Instructions" %>
  </div>
  <div class="field">
    <%= f.select :rating,["1","2","3","4","5"], {:include_blank => 'Rating'}, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<div class="row">
    <% @recipes.each do |recipe| %>
      <div class="col-md-6">
        <div class="panel panel-primary">
          <div class="panel panel-heading">
            <h3> <%= link_to recipe.name, recipe, {:style=>'color:#FFFFFF;', :class => "css_class"} %></h3>
          </div>
        <div class="well">
          <p> <h4><strong> Ingredients:</strong></h4> <%= recipe.ingredients %> </p>
          <p> <h4><strong> Instructions:</strong></h4> <%= truncate(recipe.instructions, length: 250, separator: " ") %> <br /> [<%= link_to 'Read More', recipe %>] </p>
          <strong>Rating:</strong>
            <% "#{recipe.rating}".to_i.times do |rank| %>
            <span class="glyphicon glyphicon-star"></span>
          <% end %>

          <div class="panel-footer">
            <% if current_user.id == recipe.user.id %>
              <%= link_to 'Edit', edit_recipe_path(recipe), class: "btn btn-warning" %>
              <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </div> 
        </div>
      </div>
    </div>
    <% end %>
  </div>



          

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
	<div class="panel-heading">
  	<strong>Name: <%= @recipe.name %></strong>
	</div>
</div>

<% if @recipe.avatar_file_name != nil %>
   <%= image_tag @recipe.avatar.url(:medium), class: "img-responsive" %>
<% end %>

<div class="panel panel-primary">
	<div class="panel-body">
  	<p><strong>Ingredients:</strong>
  	<%= @recipe.ingredients %></p>
  	<br>
  	<p><strong>Instructions:</strong>
  	<%= @recipe.instructions %></p>
  </div>
</div>

<p>
  <strong>Rating:</strong>
  <% "#{@recipe.rating}".to_i.times do |rank| %>
	<span class="glyphicon glyphicon-star"></span>
	<% end %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-info" %> |
<%= link_to 'Back', recipes_path, class: "btn btn-info" %>

app/views/recipes/your_recipes.html.erb
<% current_user.recipes.each do |recipe| %>
<div class="col-md-12">
  <div class="panel panel-success">
    <div class="panel-heading">
      <%= link_to recipe.name, recipe %>
    </div>
    <div class="panel-body">
      <p><span class="posted-at"><%= recipe.created_at.strftime('%m/%d/%Y at %l:%M%p') %></span></p>
      <p><%= recipe.ingredients %></p>
      <p><%= recipe.instructions[0..150] %>...[<%= link_to "READ MORE", recipe %>]</p>
    </div>
    <div class="panel-footer">
      <%= link_to 'Edit', edit_recipe_path(recipe), class: "btn btn-warning" %>
      <%= link_to 'Destroy', recipe, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  </div>
</div>
<% end %>